# Generated by Django 3.1.1 on 2020-10-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(null=True, upload_to='%Y/%m'),
        ),
    ]
